export enum Platform {
  YANDEX = 'YANDEX',
  TWOGIS = 'TWOGIS',
  WEB = 'WEB',
  CUSTOM = 'CUSTOM',
}

export enum SourceType {
  REVIEW_FEED = 'REVIEW_FEED',
  RATING_FEED = 'RATING_FEED',
  WEB_MENTION_FEED = 'WEB_MENTION_FEED',
  CUSTOM_FEED = 'CUSTOM_FEED',
}

export enum MentionType {
  REVIEW = 'REVIEW',
  ARTICLE = 'ARTICLE',
  WEB_MENTION = 'WEB_MENTION',
  SOCIAL_MENTION = 'SOCIAL_MENTION',
  COMMENT = 'COMMENT',
}

export enum MentionStatus {
  NEW = 'NEW',
  REVIEWED = 'REVIEWED',
  HIDDEN = 'HIDDEN',
  ARCHIVED = 'ARCHIVED'
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  MIXED = 'MIXED',
  UNKNOWN = 'UNKNOWN'
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER'
}

export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
  CANCELLED = 'CANCELLED'
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  TELEGRAM = 'TELEGRAM',
  WEBHOOK = 'WEBHOOK',
  IN_APP = 'IN_APP'
}

export enum NotificationType {
  NEW_NEGATIVE_MENTION = 'NEW_NEGATIVE_MENTION',
  NEW_REVIEW = 'NEW_REVIEW',
  RATING_DROP = 'RATING_DROP',
  DAILY_DIGEST = 'DAILY_DIGEST',
  AI_REPLY_READY = 'AI_REPLY_READY'
}
