export enum Platform {
  YANDEX = 'YANDEX',
  GOOGLE = 'GOOGLE',
  TWOGIS = 'TWOGIS',
  WEB = 'WEB',
  CUSTOM = 'CUSTOM',
  VK = 'VK'
}

export enum SourceType {
  REVIEW_FEED = 'REVIEW_FEED',
  RATING_FEED = 'RATING_FEED',
  WEB_MENTION_FEED = 'WEB_MENTION_FEED',
  CUSTOM_FEED = 'CUSTOM_FEED',
  VK_BRAND_SEARCH = 'VK_BRAND_SEARCH',
  VK_PRIORITY_COMMUNITIES = 'VK_PRIORITY_COMMUNITIES',
  VK_OWNED_COMMUNITY = 'VK_OWNED_COMMUNITY'
}

export enum MentionType {
  REVIEW = 'REVIEW',
  ARTICLE = 'ARTICLE',
  WEB_MENTION = 'WEB_MENTION',
  SOCIAL_MENTION = 'SOCIAL_MENTION',
  COMMENT = 'COMMENT',
  VK_POST = 'VK_POST',
  VK_COMMENT = 'VK_COMMENT'
}

export enum MentionStatus {
  NEW = 'NEW',
  REVIEWED = 'REVIEWED',
  HIDDEN = 'HIDDEN',
  ARCHIVED = 'ARCHIVED'
}

export enum Sentiment {
  POSITIVE = 'POSITIVE',
  NEUTRAL = 'NEUTRAL',
  NEGATIVE = 'NEGATIVE',
  MIXED = 'MIXED',
  UNKNOWN = 'UNKNOWN'
}

export enum WorkspaceRole {
  OWNER = 'OWNER',
  ADMIN = 'ADMIN',
  MEMBER = 'MEMBER'
}

export enum JobStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  PARTIAL = 'PARTIAL',
  CANCELLED = 'CANCELLED'
}

export enum NotificationChannel {
  EMAIL = 'EMAIL',
  TELEGRAM = 'TELEGRAM',
  WEBHOOK = 'WEBHOOK',
  IN_APP = 'IN_APP'
}

export enum NotificationType {
  NEW_NEGATIVE_MENTION = 'NEW_NEGATIVE_MENTION',
  NEW_REVIEW = 'NEW_REVIEW',
  RATING_DROP = 'RATING_DROP',
  DAILY_DIGEST = 'DAILY_DIGEST',
  VK_NEW_MENTION = 'VK_NEW_MENTION',
  AI_REPLY_READY = 'AI_REPLY_READY'
}

export enum VkMonitoringMode {
  BRAND_SEARCH = 'BRAND_SEARCH',
  PRIORITY_COMMUNITIES = 'PRIORITY_COMMUNITIES',
  OWNED_COMMUNITY = 'OWNED_COMMUNITY'
}

export enum VkTrackedCommunityMode {
  PRIORITY_COMMUNITY = 'PRIORITY_COMMUNITY',
  OWNED_COMMUNITY = 'OWNED_COMMUNITY'
}

export enum VkPostDiscoveryStatus {
  DISCOVERED = 'DISCOVERED',
  RELEVANT = 'RELEVANT',
  IRRELEVANT = 'IRRELEVANT',
  COMMENTS_SYNCED = 'COMMENTS_SYNCED',
  MENTIONS_EXTRACTED = 'MENTIONS_EXTRACTED'
}
